import 'package:web_db/core/model/product_model.dart';

List<String> productImages = [
  "https://picsum.photos/id/55/900/1000",
  "https://picsum.photos/id/65/900/1000",
  "https://picsum.photos/id/75/900/1000",
  "https://picsum.photos/id/85/900/1000",
  "https://picsum.photos/id/95/900/1000",
  "https://picsum.photos/id/104/900/1000",
  "https://picsum.photos/id/120/900/1000",
  "https://picsum.photos/id/130/900/1000",
  "https://picsum.photos/id/140/900/1000",
  "https://picsum.photos/id/145/900/1000",
  "https://picsum.photos/id/160/900/1000",
  "https://picsum.photos/id/170/900/1000",
  "https://picsum.photos/id/190/900/1000",
  "https://picsum.photos/id/200/900/1000",
  "https://picsum.photos/id/220/900/1000",
  "https://picsum.photos/id/210/900/1000",
];

List<Product> productList = [
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 1",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 2",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "Salih Usta",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 4",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 5",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 6",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 7",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 8",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 9",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 10",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 11",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 12",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 13",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 14",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 15",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
  Product(
      id: 1,
      brandId: 12,
      categoryId: 12,
      description: "loremloremloremlorem",
      name: "lorem lorem lorem lorem 16",
      price: 40.00,
      sellerId: 2,
      stockQuantity: 150),
];

List<String> productDetailImages = [
  "https://picsum.photos/id/304/1000/1500",
  "https://picsum.photos/id/305/1000/1500",
  "https://picsum.photos/id/302/1000/1500",
  "https://picsum.photos/id/301/1000/1500",
];
